print("operaciones aritméticas")
num1 = int(input("introduce el primer número: "))
num2 = int(input("introduce el segundo número: "))

print("La suma de tus números es: ", num1 + num2)
print("La resta de tus números es: ", num1 - num2)
print("La multiplicación de tus números es: ", num1 * num2)
print("La división de tus números es: ", num1 / num2)
print("El módulo de tus números es: ", num1 % num2)
print("El entero de tus números es: ", num1 // num2)
print("El elevado de tus números es: ", num1 ** num2)